# nginx proxy address - http://172.17.0.1:61007

name: letterspace
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/dcodesdev/letterspace:latest-node
    container_name: letterspace-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      DATABASE_URL: postgresql://${DB_USER_NAME:-letterspaceuser}:${DB_USER_PASS:-changeme_db_password}@letterspace-db:5432/${DB_CREATE_DATABASE_NAME:-letterspace}?schema=public
      JWT_SECRET: ${APP_JWT_TOKEN:-changeme_jwt_secret}
    ports:
      - '172.17.0.1:61007:5000'
    depends_on:
      - db
    networks:
      - letterspace
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

  db:
    image: postgres:17
    container_name: letterspace-db
    hostname: letterspace-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-letterspace}
      POSTGRES_USER: ${DB_USER_NAME:-letterspaceuser}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - './rootfs/db/postgres/letterspace:/var/lib/postgresql/data:rw'
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          'letterspace',
          '-U',
          'letterspaceuser',
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - letterspace

networks:
  letterspace:
    name: letterspace
    external: false
